# Generated by Django 5.1.1 on 2024-09-15 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0005_profile_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
