# Generated by Django 5.1.1 on 2024-09-15 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0009_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
