# Generated by Django 5.1.1 on 2024-10-16 16:58

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0011_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('picture', models.FileField(blank=True, upload_to='modules/', verbose_name='Обложка')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Текст')),
                ('order', models.IntegerField(blank=True, verbose_name='Порядковый номер')),
                ('status', models.BooleanField(default=True, verbose_name='Активный?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('slug', models.SlugField(blank=True, max_length=100, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Модуль',
                'verbose_name_plural': 'Модули',
            },
        ),
    ]
