# Generated by Django 5.1.1 on 2024-10-16 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0013_lesson_alter_module_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.PROTECT, to='cabinet.module', verbose_name='Модуль'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
