# Generated by Django 5.1.1 on 2024-10-16 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0014_lesson_module_lesson_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
    ]
