# Generated by Django 5.1.1 on 2024-10-16 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0017_lesson_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order'], 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order'], 'verbose_name': 'Модуль', 'verbose_name_plural': 'Модули'},
        ),
        migrations.AlterField(
            model_name='lesson',
            name='module',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='cabinet.module', verbose_name='Модуль'),
        ),
    ]
