# Generated by Django 5.1.1 on 2024-10-16 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0018_alter_lesson_options_alter_module_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='cabinet.module', verbose_name='Модуль'),
        ),
    ]
