# Generated by Django 5.1.1 on 2024-10-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0021_notification_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='has_homework',
            field=models.BooleanField(default=True, verbose_name='Есть ДЗ?'),
        ),
    ]
