# Generated by Django 5.1.1 on 2024-10-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0023_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Проверено'),
        ),
    ]
