# Generated by Django 5.1.1 on 2024-10-20 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0024_comment_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='cabinet.notification', verbose_name='Домашнее задание'),
        ),
    ]
