# Generated by Django 5.1.1 on 2024-10-20 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0025_alter_comment_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Домашнее задание', 'verbose_name_plural': 'Домашние задания'},
        ),
    ]
