# Generated by Django 5.1.1 on 2024-10-20 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0027_alter_comment_notification_alter_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='slug',
        ),
    ]
