# Generated by Django 5.1.1 on 2024-10-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0029_remove_comment_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Проверено?'),
        ),
    ]
