# Generated by Django 5.1.1 on 2024-10-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0032_alter_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Выполнено?'),
        ),
    ]
