# Generated by Django 5.1.1 on 2024-10-20 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0033_notification_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='cabinet.lesson', verbose_name='Урок'),
            preserve_default=False,
        ),
    ]
