# Generated by Django 5.1.1 on 2024-10-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0035_profile_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.IntegerField(blank=True, default=0, verbose_name='Порядковый номер'),
        ),
    ]
