# Generated by Django 5.1.1 on 2024-11-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0037_profile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='file',
            field=models.FileField(blank=True, upload_to='files-from-homework/', verbose_name='Файл'),
        ),
    ]
