# Generated by Django 5.1.1 on 2024-11-06 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0038_comment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='file',
            field=models.FileField(blank=True, upload_to='files-from-homework/', verbose_name='Файл'),
        ),
    ]
