# Generated by Django 5.1.1 on 2024-11-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0039_notification_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
