# Generated by Django 5.1.1 on 2024-11-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0040_comment_is_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='file',
            field=models.FileField(blank=True, upload_to='files-from-homework/answers/', verbose_name='Файл'),
        ),
    ]
