# Generated by Django 5.1.1 on 2024-11-23 17:25

import cabinet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0042_alter_comment_is_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='file',
            field=models.FileField(blank=True, upload_to=cabinet.models.user_directory_path, verbose_name='Файл'),
        ),
    ]
