# Generated by Django 5.1.1 on 2024-12-14 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0045_alter_profile_photo_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
