# Generated by Django 5.1.1 on 2024-12-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0046_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='type',
            field=models.CharField(choices=[('text', 'Текстовая'), ('req', 'Реквизиты'), ('help', 'Помощь'), ('contacts', 'Контакты')], default=0, max_length=255, verbose_name='Тип страницы'),
            preserve_default=False,
        ),
    ]
