# Generated by Django 5.1.1 on 2026-01-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0050_alter_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'В процессе'), ('waiting_for_capture', 'Деньги холдированы'), ('succeeded', 'Успешно'), ('canceled', 'Отменен')], default='pending', max_length=50, verbose_name='Статус'),
        ),
    ]
